-- Migration 001_02: Recreate swp_ORDER_LIST_V2 with Complete Schema
-- Purpose: Create shadow staging table with complete ORDER_LIST schema
-- Reason: Ensure exact ordinal positions match ORDER_LIST_V2 for ConfigParser compatibility
-- Database: orders
-- Created: 2025-07-21
-- Author: ORDER_LIST Delta Monday Sync - Schema Fix

-- =============================================================================
-- CREATE: swp_ORDER_LIST_V2 Shadow Staging Table with Complete Schema
-- Identical schema to ORDER_LIST_V2 from 001_create_shadow_tables.sql
-- Ensures UNIT OF MEASURE and TOTAL QTY are in correct ordinal positions
-- =============================================================================

CREATE TABLE dbo.swp_ORDER_LIST_V2 (
    -- Primary key (matches production schema)
    [record_uuid] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,

    -- GROUP 1: ORDER DETAILS (matches production ORDER_LIST exactly)
    [AAG ORDER NUMBER] NVARCHAR(100) NULL,
    [CUSTOMER NAME] NVARCHAR(100) NULL,
    [SOURCE_CUSTOMER_NAME] NVARCHAR(100) NULL,
    [ORDER DATE PO RECEIVED] DATETIME2 NULL,
    [PO NUMBER] NVARCHAR(255) NULL,
    [CUSTOMER ALT PO] NVARCHAR(255) NULL,
    [AAG SEASON] NVARCHAR(255) NULL,
    [CUSTOMER SEASON] NVARCHAR(100) NULL,
    [DROP] NVARCHAR(255) NULL,
    [MONTH] NVARCHAR(255) NULL,
    [RANGE / COLLECTION] NVARCHAR(255) NULL,
    [PROMO GROUP / CAMPAIGN (HOT 30/GLOBAL EDIT)] NVARCHAR(255) NULL,
    [CATEGORY] NVARCHAR(255) NULL,
    [PATTERN ID] NVARCHAR(255) NULL,
    [PLANNER] NVARCHAR(500) NULL,
    [MAKE OR BUY] NVARCHAR(255) NULL,
    [ORIGINAL ALIAS/RELATED ITEM] NVARCHAR(255) NULL,
    [PRICING ALIAS/RELATED ITEM] NVARCHAR(255) NULL,
    [ALIAS/RELATED ITEM] NVARCHAR(255) NULL,
    [CUSTOMER STYLE] NVARCHAR(100) NULL,
    [STYLE DESCRIPTION] NVARCHAR(100) NULL,
    [CUSTOMER'S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS] NVARCHAR(255) NULL,
    [CUSTOMER COLOUR DESCRIPTION] NVARCHAR(100) NULL,
    [INFOR WAREHOUSE CODE] NVARCHAR(255) NULL,
    [BULK AGREEMENT NUMBER] NVARCHAR(255) NULL,
    [INFOR FACILITY CODE] NVARCHAR(255) NULL,
    [INFOR BUSINESS UNIT AREA] NVARCHAR(255) NULL,
    [BULK AGREEMENT DESCRIPTION] NVARCHAR(255) NULL,
    [CO NUMBER - INITIAL DISTRO] NVARCHAR(255) NULL,
    [INFOR CUSTOMER CODE] NVARCHAR(255) NULL,
    [CO NUMBER - ALLOCATION DISTRO] NVARCHAR(255) NULL,
    [CO NUMBER (INITIAL DISTRO)] NVARCHAR(255) NULL,
    [CO NUMBER (ALLOCATION DISTRO)] NVARCHAR(255) NULL,
    [INFOR ORDER TYPE] NVARCHAR(255) NULL,
    [INFOR SEASON CODE] NVARCHAR(255) NULL,
    [ITEM TYPE CODE] NVARCHAR(255) NULL,
    [PRODUCT GROUP CODE] NVARCHAR(255) NULL,
    [ITEM GROUP CODE] NVARCHAR(255) NULL,
    [PLANNER2] NVARCHAR(255) NULL,
    [GENDER GROUP CODE] NVARCHAR(255) NULL,
    [FABRIC TYPE CODE] NVARCHAR(255) NULL,
    [INFOR MAKE/BUY CODE] NVARCHAR(255) NULL,
    [INFOR ITEM TYPE CODE] NVARCHAR(255) NULL,
    [INFOR PRODUCT GROUP CODE] NVARCHAR(255) NULL,
    [INFOR ITEM GROUP CODE] NVARCHAR(255) NULL,
    [INFOR GENDER GROUP CODE] NVARCHAR(255) NULL,
    [INFOR FABRIC TYPE CODE] NVARCHAR(255) NULL,
    [LONGSON ALIAS] NVARCHAR(255) NULL,
    [INFOR COLOUR CODE] NVARCHAR(255) NULL,
    [FACILITY CODE] NVARCHAR(255) NULL,
    [CUSTOMER CODE] NVARCHAR(255) NULL,
    [Column2] NVARCHAR(100) NULL,
    [Column1] NVARCHAR(100) NULL,
    [AAG SEASON CODE] NVARCHAR(255) NULL,
    [MAKE OR BUY FLAG] NVARCHAR(100) NULL,
    [MAKE/BUY CODE] NVARCHAR(100) NULL,
    [UNIT OF MEASURE] NVARCHAR(100) NULL,

    -- GROUP 2: GARMENT SIZES (All INT for quantity calculations - 251 columns)
    -- Baby Sizes
    [2T] INT NULL, [3T] INT NULL, [4T] INT NULL, [5T] INT NULL, [6T] INT NULL,
    -- Numeric Child
    [0] INT NULL, [0-3M] INT NULL, [1] INT NULL, [2] INT NULL, [2/3] INT NULL,
    [3/6 MTHS] INT NULL, [3-6M] INT NULL, [3-4 years] INT NULL, [3] INT NULL, [3-4] INT NULL,
    [4] INT NULL, [4/5] INT NULL, [04/XXS] INT NULL, [5] INT NULL, [5-6 years] INT NULL,
    [5-6] INT NULL, [6] INT NULL, [6-12M] INT NULL, [6/7] INT NULL, [6/12 MTHS] INT NULL,
    [6-9M] INT NULL, [6-10] INT NULL, [S(6-8)] INT NULL, [7] INT NULL, [7-8 years] INT NULL,
    [7-8] INT NULL, [8] INT NULL, [08/S] INT NULL, [8/9] INT NULL, [M(8-10)] INT NULL,
    [9] INT NULL, [9-12M] INT NULL, [9-10 years] INT NULL, [9-10] INT NULL, [10] INT NULL,
    [10/M] INT NULL, [10/11] INT NULL, [10-12] INT NULL, [M(10-12)] INT NULL, [L(10-12)] INT NULL,
    [11-12 years] INT NULL, [11-14] INT NULL, [12] INT NULL, [12/18 MTHS] INT NULL, [12-18M] INT NULL,
    [12/L] INT NULL, [12/13] INT NULL, [12-14] INT NULL, [13-14 years] INT NULL, [14] INT NULL,
    [L(14-16)] INT NULL, [16] INT NULL,
    -- Adult Sizes
    [XS] INT NULL, [XS/S] INT NULL, [XS-PETITE] INT NULL, [06/XS] INT NULL, [XXS/XS] INT NULL,
    [CD/XS] INT NULL, [C/XS] INT NULL, [D/XS] INT NULL, [XL] INT NULL, [L/XL] INT NULL,
    [14/XL] INT NULL, [L-XL] INT NULL, [AB/XL] INT NULL, [CD/XL] INT NULL, [C/XL] INT NULL,
    [D/XL] INT NULL, [XXL] INT NULL, [2XL] INT NULL, [XL/XXL] INT NULL, [16/XXL] INT NULL,
    [XL/2XL] INT NULL, [XXL/3XL] INT NULL, [D/XXL] INT NULL, [3XL] INT NULL, [4XL] INT NULL,
    -- Numeric Adult (continued for all waist sizes)
    [18] INT NULL, [18/24 MTHS] INT NULL, [18-24M] INT NULL, [18/XXXL] INT NULL, [20] INT NULL,
    [22] INT NULL, [24] INT NULL, [25] INT NULL, [26] INT NULL, [27] INT NULL,
    [28] INT NULL, [28-30L] INT NULL, [29] INT NULL, [30] INT NULL, [30-30L] INT NULL,
    [30-31L] INT NULL, [30/32] INT NULL, [30-32L] INT NULL, [30/30] INT NULL, [31] INT NULL,
    [31-30L] INT NULL, [31-31L] INT NULL, [31/32] INT NULL, [31-32L] INT NULL, [31/30] INT NULL,
    [32] INT NULL, [32-30L] INT NULL, [32-31L] INT NULL, [32/32] INT NULL, [32-32L] INT NULL,
    [32/34] INT NULL, [32/36] INT NULL, [32/30] INT NULL, [33] INT NULL, [33-30L] INT NULL,
    [33-31L] INT NULL, [33/32] INT NULL, [33-32L] INT NULL, [33/30] INT NULL, [34] INT NULL,
    [34-30L] INT NULL, [34-31L] INT NULL, [34/32] INT NULL, [34-32L] INT NULL, [34/34] INT NULL,
    [34/30] INT NULL, [35] INT NULL, [35-30L] INT NULL, [35-31L] INT NULL, [35/32] INT NULL,
    [35-32L] INT NULL, [35/30] INT NULL, [36] INT NULL, [36-30L] INT NULL, [36-31L] INT NULL,
    [36/32] INT NULL, [36-32L] INT NULL, [36/34] INT NULL, [36/30] INT NULL, [38] INT NULL,
    [38-30L] INT NULL, [38-31L] INT NULL, [38/32] INT NULL, [38-32L] INT NULL, [38/34] INT NULL,
    [38/36] INT NULL, [38/30] INT NULL, [40] INT NULL, [40-30L] INT NULL, [40-31L] INT NULL,
    [40/32] INT NULL, [40/30] INT NULL, [42] INT NULL, [43] INT NULL, [44] INT NULL,
    [45] INT NULL, [46] INT NULL, [48] INT NULL, [50] INT NULL, [52] INT NULL,
    [54] INT NULL, [56] INT NULL, [58] INT NULL, [60] INT NULL,
    -- One Size
    [OS] INT NULL, [ONE SIZE] INT NULL, [One_Size] INT NULL, [One Sz] INT NULL,
    -- Other Sizes
    [S] INT NULL, [M] INT NULL, [L] INT NULL, [XXS] INT NULL, [S/M] INT NULL,
    [M/L] INT NULL, [XXXL] INT NULL, [2X] INT NULL, [3X] INT NULL, [1X] INT NULL,
    [4X] INT NULL, [XXXS] INT NULL, [S/P] INT NULL, [S+] INT NULL, [1Y] INT NULL,
    [2Y] INT NULL, [3Y] INT NULL, [4Y] INT NULL, [S-PETITE] INT NULL, [S-M] INT NULL,
    [32C] INT NULL, [32D] INT NULL, [4XT] INT NULL, [32DD] INT NULL, [30x30] INT NULL,
    [32DDD] INT NULL, [34C] INT NULL, [30x32] INT NULL, [0w] INT NULL, [2w] INT NULL,
    [32x30] INT NULL, [One_Sz] INT NULL, [34D] INT NULL, [34DD] INT NULL, [4w] INT NULL,
    [32x32] INT NULL, [6w] INT NULL, [34DDD] INT NULL, [32x34] INT NULL, [36C] INT NULL,
    [8w] INT NULL, [34x30] INT NULL, [10w] INT NULL, [O/S] INT NULL, [34x32] INT NULL,
    [31x30] INT NULL, [36D] INT NULL, [12w] INT NULL, [34x34] INT NULL, [36DD] INT NULL,
    [36DDD] INT NULL, [36x32] INT NULL, [38C] INT NULL, [36x30] INT NULL, [38D] INT NULL,
    [36x34] INT NULL, [38x30] INT NULL, [40x30] INT NULL, [38DD] INT NULL, [38x32] INT NULL,
    [38DDD] INT NULL, [38x34] INT NULL, [40x32] INT NULL, [40x34] INT NULL, [AB/S] INT NULL,
    [AB/M] INT NULL, [CD/S] INT NULL, [CD/M] INT NULL, [CD/L] INT NULL, [C/S] INT NULL,
    [C/M] INT NULL, [C/L] INT NULL, [D/S] INT NULL, [D/M] INT NULL, [D/L] INT NULL,

    -- GROUP 3: ADDITIONAL ORDER DETAILS (110 columns)
    [TOTAL QTY] SMALLINT NULL,
    [DESTINATION] NVARCHAR(100) NULL,
    [DESTINATION WAREHOUSE] NVARCHAR(255) NULL,
    [ALLOCATION (CHANNEL)] NVARCHAR(255) NULL,
    [SHOP NAME] NVARCHAR(255) NULL,
    [SHOP CODE] NVARCHAR(255) NULL,
    [COLLECTION DELIVERY] NVARCHAR(255) NULL,
    [ETA CUSTOMER WAREHOUSE DATE] DATETIME2 NULL,
    [EX FACTORY DATE] DATETIME2 NULL,
    [DELIVERY TERMS] NVARCHAR(255) NULL,
    [PLANNED DELIVERY METHOD] NVARCHAR(100) NULL,
    [NOTES] NVARCHAR(1000) NULL,
    [ORDER TYPE] NVARCHAR(100) NULL,
    [VALIDATION] NVARCHAR(100) NULL,
    [VALIDATION2] NVARCHAR(255) NULL,
    [VALIDATION3] NVARCHAR(255) NULL,
    [VALIDATION4] NVARCHAR(255) NULL,
    [CUSTOMER PRICE] DECIMAL(10,4) NULL,
    [USA ONLY LSTP 75% EX WORKS] DECIMAL(10,4) NULL,
    [EX WORKS (USD)] DECIMAL(10,4) NULL,
    [ADMINISTRATION FEE] DECIMAL(10,4) NULL,
    [DESIGN FEE] NVARCHAR(255) NULL,
    [FX CHARGE] DECIMAL(10,4) NULL,
    [HANDLING] DECIMAL(10,4) NULL,
    [PNP] NVARCHAR(255) NULL,
    [SURCHARGE FEE] NVARCHAR(255) NULL,
    [DISCOUNT] NVARCHAR(255) NULL,
    [FINAL FOB (USD)] DECIMAL(17,4) NULL,
    [HS CODE] NVARCHAR(255) NULL,
    [US DUTY RATE] DECIMAL(10,6) NULL,
    [US DUTY] DECIMAL(10,4) NULL,
    [FREIGHT] DECIMAL(18,4) NULL,
    [US TARIFF RATE] DECIMAL(10,6) NULL,
    [US TARIFF] DECIMAL(10,4) NULL,
    [DDP US (USD)] DECIMAL(17,4) NULL,
    [UK DUTY RATE] NVARCHAR(255) NULL,
    [UK FREIGHT] NVARCHAR(255) NULL,
    [UK INSURANCE] NVARCHAR(255) NULL,
    [UK CIF] NVARCHAR(255) NULL,
    [UK DUTY] NVARCHAR(255) NULL,
    [DDP UK (USD)] NVARCHAR(255) NULL,
    [CAN DUTY RATE] NVARCHAR(255) NULL,
    [CAN DUTY] NVARCHAR(255) NULL,
    [DDP CAN (USD)] NVARCHAR(255) NULL,
    [SMS PRICE USD] DECIMAL(10,4) NULL,
    [FINAL PRICES Y/N] NVARCHAR(255) NULL,
    [NOTES FOR PRICE] NVARCHAR(255) NULL,
    [∆] NVARCHAR(255) NULL,
    [INFOR ADDRESS ID] NVARCHAR(255) NULL,
    [TRACKING NUMBER] NVARCHAR(255) NULL,
    [INFOR DELIVERY CODE] NVARCHAR(255) NULL,
    [COUNTRY OF ORIGIN] NVARCHAR(100) NULL,
    [DELIVERY CODE (MODL)] DECIMAL(18,4) NULL,
    [COUNTRY OF ORIGN] NVARCHAR(100) NULL,
    [FX CHARGE 2 Dec] NVARCHAR(100) NULL,
    [INFOR EX-WORKS 4 Dec] NVARCHAR(100) NULL,
    [AU Product 4 Dec] NVARCHAR(100) NULL,
    [AU PnP 4 Dec] NVARCHAR(100) NULL,
    [AU Price 2 Dec] NVARCHAR(100) NULL,
    [AU Discount 2 Dec] NVARCHAR(100) NULL,
    [US Product 4 Dec] NVARCHAR(100) NULL,
    [US PnP 4 Dec] NVARCHAR(100) NULL,
    [US Duty 2 Dec] NVARCHAR(100) NULL,
    [US Tariff 2 Dec] NVARCHAR(100) NULL,
    [TARIFF RELIEF DISCOUNT (20%)] DECIMAL(17,4) NULL,
    [US Price 2 Dec] NVARCHAR(100) NULL,
    [FOB TO USE ON PRODUCT INVOICE] DECIMAL(17,4) NULL,
    [US Discount 2 Dec] NVARCHAR(100) NULL,
    [US Price w/ Discount] NVARCHAR(100) NULL,
    [CAN Product 4 Dec] NVARCHAR(100) NULL,
    [ADDITIONAL TARIFF RATE] DECIMAL(17,4) NULL,
    [CAN PnP 4 Dec] NVARCHAR(100) NULL,
    [CAN Duty 2 Dec] NVARCHAR(100) NULL,
    [ADDITIONAL TARIFF %] NVARCHAR(255) NULL,
    [ADDITIONAL TARIFF] DECIMAL(10,4) NULL,
    [CAN Price 2 Dec] NVARCHAR(100) NULL,
    [ADDITIONAL TARIFF VALUE] DECIMAL(18,4) NULL,
    [CAN Discount 2 Dec] NVARCHAR(100) NULL,
    [TARIFF RATE CHARGED TO AAG] NVARCHAR(255) NULL,
    [CAN Price w/ Discount] NVARCHAR(100) NULL,
    [TARIFF LOSS] NVARCHAR(255) NULL,
    [UK Product 4 Dec] NVARCHAR(100) NULL,
    [UK PnP 4 Dec] NVARCHAR(100) NULL,
    [INVOICE METHOD] NVARCHAR(100) NULL,
    [UK Duty 2 Dec] NVARCHAR(100) NULL,
    [UK Price 2 Dec] NVARCHAR(100) NULL,
    [UK Discount 2 Dec] NVARCHAR(100) NULL,
    [UK Price w/ Discount] NVARCHAR(100) NULL,
    [RMB price (ex. VAT)] NVARCHAR(100) NULL,
    [RMB Discount 2 Dec] NVARCHAR(100) NULL,
    [RMB Price w/ Discount] NVARCHAR(100) NULL,
    [PRICING NOTES] NVARCHAR(100) NULL,
    [NASC TO ROC PRICE (RMB) (inc VAT)] DECIMAL(10,4) NULL,
    [FINANCE EST (USD)] DECIMAL(18,4) NULL,
    [Warehouse] NVARCHAR(100) NULL,
    [NASC TO WHITE FOX (USD)] DECIMAL(10,4) NULL,
    [INVOICE MONTH] NVARCHAR(100) NULL,
    [INVOICE YEAR] SMALLINT NULL,
    [ORTP (ORDER TYPE)] NVARCHAR(255) NULL,
    [HDPR] NVARCHAR(255) NULL,
    [PATTERN/STYLE NAME] NVARCHAR(100) NULL,
    [RRP] NVARCHAR(100) NULL,
    [PFI EXCHANGE RATE] NVARCHAR(100) NULL,
    [FOB (AUD)] DECIMAL(10,4) NULL,
    [BUAR (BUSINESS AREA UNIT)] NVARCHAR(255) NULL,
    [MARGIN] NVARCHAR(255) NULL,
    [ADID] NVARCHAR(255) NULL,
    [_SOURCE_TABLE] NVARCHAR(255) NULL,
    
    -- Delta sync columns (NEW - enable change detection and Monday.com sync)
    -- NOTE: row_hash populated by application logic using TOML configuration
    -- Hash algorithm and columns defined in sync_order_list.toml
    row_hash            CHAR(64) NULL,  -- Populated by application logic, not computed column
    sync_state          VARCHAR(10) NOT NULL DEFAULT ('NEW'),
    last_synced_at      DATETIME2 NULL,
    monday_item_id      BIGINT NULL,
    
    -- Audit columns
    created_at          DATETIME2 DEFAULT GETUTCDATE(),
    updated_at          DATETIME2 DEFAULT GETUTCDATE()
);

-- Index for efficient hash-based change detection
CREATE INDEX IX_swp_ORDER_LIST_V2_hash ON dbo.swp_ORDER_LIST_V2 (row_hash);
CREATE INDEX IX_swp_ORDER_LIST_V2_sync_state ON dbo.swp_ORDER_LIST_V2 (sync_state);
CREATE INDEX IX_swp_ORDER_LIST_V2_monday_item_id ON dbo.swp_ORDER_LIST_V2 (monday_item_id);

-- Phase 1 specific indexes for GREYSON PO 4755 testing
CREATE INDEX IX_swp_ORDER_LIST_V2_customer_po ON dbo.swp_ORDER_LIST_V2 ([CUSTOMER NAME], [PO NUMBER]);
CREATE INDEX IX_swp_ORDER_LIST_V2_aag_order ON dbo.swp_ORDER_LIST_V2 ([AAG ORDER NUMBER]);

-- =============================================================================
-- Verification: Check schema compatibility
-- =============================================================================

DECLARE @swp_columns INT;
SELECT @swp_columns = COUNT(*) 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'swp_ORDER_LIST_V2' AND TABLE_SCHEMA = 'dbo';

PRINT 'VERIFICATION: swp_ORDER_LIST_V2 created with ' + CAST(@swp_columns AS VARCHAR(10)) + ' columns';

-- Check UNIT OF MEASURE and TOTAL QTY positions
DECLARE @unit_pos INT, @total_pos INT;
SELECT @unit_pos = ORDINAL_POSITION 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'swp_ORDER_LIST_V2' AND COLUMN_NAME = 'UNIT OF MEASURE';

SELECT @total_pos = ORDINAL_POSITION 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'swp_ORDER_LIST_V2' AND COLUMN_NAME = 'TOTAL QTY';

PRINT 'VERIFICATION: UNIT OF MEASURE at position ' + CAST(@unit_pos AS VARCHAR(10));
PRINT 'VERIFICATION: TOTAL QTY at position ' + CAST(@total_pos AS VARCHAR(10));

IF @total_pos > @unit_pos + 250  -- Approximately 251 size columns between them
BEGIN
    PRINT 'SUCCESS: Ordinal positions are correct for size column detection';
END
ELSE
BEGIN
    PRINT 'WARNING: Ordinal positions may not be correct - check schema';
END

-- =============================================================================
-- Success message
-- =============================================================================

PRINT 'Migration 001_02: swp_ORDER_LIST_V2 recreated with complete schema successfully';
PRINT '';
PRINT 'Schema Status:';
PRINT '  - Complete 417-column schema applied';
PRINT '  - UNIT OF MEASURE and TOTAL QTY in correct ordinal positions';
PRINT '  - All 251 size columns between UNIT OF MEASURE and TOTAL QTY';
PRINT '  - Indexes and trigger created';
PRINT '';
PRINT 'Next Steps:';
PRINT '  1. Run 001_03_insert_test_data.sql to populate with test data';
PRINT '  2. Validate schema matches ORDER_LIST_V2 using 001_04_validate_schema.sql';
PRINT '  3. Test ConfigParser with real database size column detection';
