

-- Add 6 new columns for comprehensive API logging
ALTER TABLE FACT_ORDER_LIST ADD api_request_payload NVARCHAR(MAX) NULL;
ALTER TABLE FACT_ORDER_LIST ADD api_response_payload NVARCHAR(MAX) NULL;
ALTER TABLE FACT_ORDER_LIST ADD api_request_timestamp DATETIME2 NULL;
ALTER TABLE FACT_ORDER_LIST ADD api_response_timestamp DATETIME2 NULL;
ALTER TABLE FACT_ORDER_LIST ADD api_operation_type NVARCHAR(50) NULL;
ALTER TABLE FACT_ORDER_LIST ADD api_status NVARCHAR(20) NULL;


-- Add 6 new columns for comprehensive API logging
ALTER TABLE ORDER_LIST ADD api_request_payload NVARCHAR(MAX) NULL;
ALTER TABLE ORDER_LIST ADD api_response_payload NVARCHAR(MAX) NULL;
ALTER TABLE ORDER_LIST ADD api_request_timestamp DATETIME2 NULL;
ALTER TABLE ORDER_LIST ADD api_response_timestamp DATETIME2 NULL;
ALTER TABLE ORDER_LIST ADD api_operation_type NVARCHAR(50) NULL;
ALTER TABLE ORDER_LIST ADD api_status NVARCHAR(20) NULL;


-- Mirror the same columns for line-level operations
ALTER TABLE ORDER_LIST_LINES ADD api_request_payload NVARCHAR(MAX) NULL;
ALTER TABLE ORDER_LIST_LINES ADD api_response_payload NVARCHAR(MAX) NULL;
ALTER TABLE ORDER_LIST_LINES ADD api_request_timestamp DATETIME2 NULL;
ALTER TABLE ORDER_LIST_LINES ADD api_response_timestamp DATETIME2 NULL;
ALTER TABLE ORDER_LIST_LINES ADD api_operation_type NVARCHAR(50) NULL;
ALTER TABLE ORDER_LIST_LINES ADD api_status NVARCHAR(20) NULL;