SELECT 
    [CUSTOMER NAME], [_SOURCE_TABLE],
    COUNT(*) AS record_count,
    COUNT(DISTINCT [SOURCE_CUSTOMER_NAME]) AS unique_source_names
FROM [swp_ORDER_LIST_SYNC]
GROUP BY [CUSTOMER NAME], [_SOURCE_TABLE]
