# ORDER_LIST Delta Monday Sync - Development Configuration
# Milestone 1: Foundation configuration for shadow table development
# Created: 2025-07-18
# Environment: Development (uses shadow tables and test Monday board)

[environment]
# Development environment uses shadow tables for zero production impact
target_table = "ORDER_LIST_V2"                  # Shadow table for development
lines_table = "ORDER_LIST_LINES"                # New lines table
delta_table = "ORDER_LIST_DELTA"                # Header change tracking
lines_delta_table = "ORDER_LIST_LINES_DELTA"    # Line change tracking
board_type = "development"                      # Use development Monday board

[database]
# Database connection configuration
connection_name = "orders"              # From pipelines/utils/config.yaml
schema = "dbo"                          # Default schema

[hash]
# Business logic for change detection
# These columns define what constitutes a "change" requiring Monday sync
columns = [
    "AAG ORDER NUMBER", 
    "CUSTOMER NAME", 
    "STYLE DESCRIPTION",
    "TOTAL QTY", 
    "ETA CUSTOMER WAREHOUSE DATE",
    "CUSTOMER STYLE"
]
algorithm = "SHA2_256"
encoding = "utf-8"

[sizes]
# Dynamic size detection configuration
# Size columns are detected between these markers in Excel
start_marker = "UNIT OF MEASURE"         # Column that precedes size columns
end_marker = "TOTAL QTY"                 # Column that follows size columns

# Size detection is 100% dynamic - no hardcoded fallback codes
# All size codes discovered from actual Excel data between markers

# Size validation rules
min_qty = 0                             # Minimum quantity (0 = ignore size)
max_qty = 99999                         # Maximum reasonable quantity

[monday.development]
# Development/testing Monday.com board configuration
board_id = 123456789                     # PLACEHOLDER - Replace with actual test board ID
group_id = "development_group"           # PLACEHOLDER - Replace with actual group ID
api_timeout = 30                         # API timeout in seconds
retry_count = 3                          # Number of retry attempts
batch_size = 15                          # Items per batch for async processing

[monday.column_mapping.headers]
# Maps ORDER_LIST columns to Monday.com item column IDs
# PLACEHOLDER VALUES - Replace with actual Monday column IDs after board setup
"AAG ORDER NUMBER" = "text_order_number"
"CUSTOMER NAME" = "text_customer"
"STYLE DESCRIPTION" = "text_style_desc"
"TOTAL QTY" = "numbers_total_qty"
"ETA CUSTOMER WAREHOUSE DATE" = "date_eta"
"PO_NUMBER" = "text_po"
"STYLE" = "text_style"
"COLOR" = "text_color"

[monday.column_mapping.lines]
# Maps ORDER_LIST_LINES columns to Monday.com subitem column IDs
# PLACEHOLDER VALUES - Replace with actual Monday subitem column IDs
"size_code" = "text_size"
"qty" = "numbers_qty"

[monday.graphql_templates]
# GraphQL template configuration for Monday.com API operations
# Templates loaded from sql/graphql/ using GraphQLLoader
create_item = "create-master-item"       # Header item creation
update_item = "update_item"              # Header item updates
create_subitem = "create-subitem"        # Size line creation
update_subitem = "update_subitem"        # Size line updates

# Async batch processing settings
batch_size = 15                          # Records per batch
max_concurrent_batches = 3               # Maximum parallel batches
batch_delay_ms = 100                     # Delay between batches (rate limiting)

[delta_tables]
# Delta table management configuration
retention_days = 7                       # Keep delta records for 7 days after SYNCED
batch_size = 1000                        # Records per processing batch
max_retry_count = 3                      # Maximum retry attempts for failed syncs
retry_delay_minutes = 5                  # Delay between retry attempts

[validation]
# Data validation rules
required_fields = [
    "AAG ORDER NUMBER",
    "CUSTOMER NAME", 
    "STYLE DESCRIPTION",
    "TOTAL QTY"
]

# Business rules
max_total_qty = 50000                    # Maximum reasonable total quantity
min_total_qty = 1                        # Minimum total quantity
date_format = "YYYY-MM-DD"               # Expected date format

[logging]
# Logging configuration (Kestra-compatible)
level = "INFO"                           # DEBUG, INFO, WARNING, ERROR
format = "structured"                    # For Kestra log parsing
include_sql_statements = false           # Set to true for debugging
include_api_requests = false             # Set to true for Monday.com debugging

[sync_state]
# Sync state management
states = ["NEW", "CHANGED", "SYNCED", "FAILED"]
default_state = "NEW"
pending_delta_state = "PENDING"

# Sync scheduling (for future Kestra integration)
schedule_enabled = false                 # Enable for production
schedule_cron = "0 */4 * * *"           # Every 4 hours
max_sync_duration_minutes = 60          # Maximum sync time before timeout

[development]
# Development-specific settings
dry_run_default = true                   # Default to dry-run mode in development
test_data_limit = 100                    # Limit test data processing
debug_mode = true                        # Enable verbose debugging
mock_monday_api = false                  # Set to true to mock Monday.com calls

# Test data configuration
test_customer = "GREYSON"                # Default test customer
test_po = "4755"                         # Default test PO
test_record_limit = 5                    # Limit for focused testing

[milestones]
# Development milestone tracking
milestone_1_complete = false             # Shadow tables and TOML config
milestone_2_complete = false             # Delta sync engine
milestone_3_complete = false             # Monday.com integration
milestone_4_complete = false             # Production deployment

# Milestone 1 requirements (Foundation)
milestone_1_requirements = [
    "Shadow tables created (ORDER_LIST_V2, ORDER_LIST_LINES)",
    "TOML configuration loaded successfully",
    "Database migrations working",
    "Hash generation functional"
]

# Next milestone checklist
milestone_2_requirements = [
    "Hash-based change detection working",
    "Size column discovery functional", 
    "Merge operations (headers and lines)",
    "GraphQL integration with async batching"
]
