# DB Migration: Run All Migrations

name: "migrations-all"
description: "Execute all database migrations in order"
category: "migration"
type: "dev"

task:
  label: "DB: Run All Migrations"
  type: "shell"
  command: "python"
  args:
    - "tools/run-migration.py"
    - "--dir"
    - "sql/migrations"
    - "--db"
    - "orders"
  group: "build"
  options:
    cwd: "${workspaceFolder}"
  detail: "Execute all database migrations in order from sql/migrations directory"
  presentation:
    echo: true
    reveal: "always"
    focus: false
    panel: "shared"
  problemMatcher: []
  tags:
    - "database"
    - "migration"
    - "schema"
    - "all"
