-- Check if swp_ORDER_LIST_LINES table exists

-- Step 1: Check if table exists
PRINT '=== CHECKING swp_ORDER_LIST_LINES TABLE EXISTENCE ===';
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'swp_ORDER_LIST_LINES' AND TABLE_SCHEMA = 'dbo')
BEGIN
    PRINT 'Table swp_ORDER_LIST_LINES EXISTS';
    
    -- Check column count
    SELECT COUNT(*) as column_count FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'swp_ORDER_LIST_LINES' AND TABLE_SCHEMA = 'dbo';
    
    -- Check row count
    DECLARE @RowCount INT;
    SELECT @RowCount = COUNT(*) FROM dbo.swp_ORDER_LIST_LINES;
    PRINT 'Row count: ' + CAST(@RowCount AS VARCHAR(10));
END
ELSE
BEGIN
    PRINT 'Table swp_ORDER_LIST_LINES DOES NOT EXIST';
    PRINT 'Need to create swp_ORDER_LIST_LINES as shadow of ORDER_LIST_LINES';
END

-- Step 2: Check ORDER_LIST_LINES as reference
PRINT '=== CHECKING ORDER_LIST_LINES REFERENCE TABLE ===';
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'ORDER_LIST_LINES' AND TABLE_SCHEMA = 'dbo')
BEGIN
    PRINT 'Reference table ORDER_LIST_LINES EXISTS';
    
    -- Show schema
    SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
    FROM INFORMATION_SCHEMA.COLUMNS 
    WHERE TABLE_NAME = 'ORDER_LIST_LINES' AND TABLE_SCHEMA = 'dbo'
    ORDER BY ORDINAL_POSITION;
END
ELSE
BEGIN
    PRINT 'Reference table ORDER_LIST_LINES DOES NOT EXIST';
END
