-- Check and Fix Constraints Blocking Task 5.0
-- Error: "The target table 'dbo.ORDER_LIST_DELTA' of the OUTPUT INTO clause cannot have any enabled check constraints"
-- Date: July 21, 2025

-- Step 1: Check what constraints exist on ORDER_LIST_DELTA
PRINT '=== CHECKING CONSTRAINTS ON ORDER_LIST_DELTA ===';
SELECT
    cc.CONSTRAINT_NAME,
    cc.CHECK_CLAUSE,
    t.TABLE_NAME
FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS t 
    ON cc.CONSTRAINT_NAME = t.CONSTRAINT_NAME
WHERE t.TABLE_NAME = 'ORDER_LIST_DELTA';

-- Step 2: Check ORDER_LIST_LINES_DELTA constraints too
PRINT '=== CHECKING ORDER_LIST_LINES_DELTA CONSTRAINTS ===';
SELECT
    cc.CONSTRAINT_NAME,
    cc.CHECK_CLAUSE,
    t.TABLE_NAME
FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS t 
    ON cc.CONSTRAINT_NAME = t.CONSTRAINT_NAME
WHERE t.TABLE_NAME = 'ORDER_LIST_LINES_DELTA';

-- Step 3: Drop the problematic constraint on ORDER_LIST_DELTA
PRINT '=== DROPPING CHK_ORDER_LIST_DELTA_action_type CONSTRAINT ===';
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CHK_ORDER_LIST_DELTA_action_type')
BEGIN
    ALTER TABLE dbo.ORDER_LIST_DELTA DROP CONSTRAINT CHK_ORDER_LIST_DELTA_action_type;
    PRINT 'Constraint CHK_ORDER_LIST_DELTA_action_type dropped successfully';
END
ELSE
    PRINT 'Constraint CHK_ORDER_LIST_DELTA_action_type not found';

-- Step 4: Drop CHK_ORDER_LIST_DELTA_sync_state constraint  
PRINT '=== DROPPING CHK_ORDER_LIST_DELTA_sync_state CONSTRAINT ===';
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CHK_ORDER_LIST_DELTA_sync_state')
BEGIN
    ALTER TABLE dbo.ORDER_LIST_DELTA DROP CONSTRAINT CHK_ORDER_LIST_DELTA_sync_state;
    PRINT 'Constraint CHK_ORDER_LIST_DELTA_sync_state dropped successfully';
END
ELSE
    PRINT 'Constraint CHK_ORDER_LIST_DELTA_sync_state not found';

-- Step 5: Drop any similar constraint on ORDER_LIST_LINES_DELTA
PRINT '=== DROPPING CHK_ORDER_LIST_LINES_DELTA_action_type CONSTRAINT ===';
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CHK_ORDER_LIST_LINES_DELTA_action_type')
BEGIN
    ALTER TABLE dbo.ORDER_LIST_LINES_DELTA DROP CONSTRAINT CHK_ORDER_LIST_LINES_DELTA_action_type;
    PRINT 'Constraint CHK_ORDER_LIST_LINES_DELTA_action_type dropped successfully';
END
ELSE
    PRINT 'Constraint CHK_ORDER_LIST_LINES_DELTA_action_type not found';

-- Step 6: Drop CHK_ORDER_LIST_LINES_DELTA_sync_state constraint
PRINT '=== DROPPING CHK_ORDER_LIST_LINES_DELTA_sync_state CONSTRAINT ===';
IF EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS WHERE CONSTRAINT_NAME = 'CHK_ORDER_LIST_LINES_DELTA_sync_state')
BEGIN
    ALTER TABLE dbo.ORDER_LIST_LINES_DELTA DROP CONSTRAINT CHK_ORDER_LIST_LINES_DELTA_sync_state;
    PRINT 'Constraint CHK_ORDER_LIST_LINES_DELTA_sync_state dropped successfully';
END
ELSE
    PRINT 'Constraint CHK_ORDER_LIST_LINES_DELTA_sync_state not found';

-- Step 7: Verify all constraints are gone
PRINT '=== FINAL VERIFICATION - NO CONSTRAINTS SHOULD REMAIN ===';
SELECT
    cc.CONSTRAINT_NAME,
    cc.CHECK_CLAUSE,
    t.TABLE_NAME
FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc
INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS t 
    ON cc.CONSTRAINT_NAME = t.CONSTRAINT_NAME
WHERE t.TABLE_NAME IN ('ORDER_LIST_DELTA', 'ORDER_LIST_LINES_DELTA');

PRINT '=== CONSTRAINT FIX COMPLETE ===';
PRINT 'Task 5.0 should now be unblocked for complete pipeline testing';
