SELECT TOP (1000) [AAG ORDER NUMBER]
      ,[CUSTOMER NAME]
      ,[ORDER DATE PO RECEIVED]
      ,[CUSTOMER ALT PO]
      ,[AAG SEASON]
      ,[CUSTOMER SEASON]
      ,[DROP]
      ,[MONTH]
      ,[RANGE / COLLECTION]
      ,[PROMO GROUP / CAMPAIGN (HOT 30/GLOBAL EDIT]
      ,[CATEGORY]
      ,[PATTERN ID]
      ,[MAKE OR BUY]
      ,[PLANNER]
      ,[ORIGINAL ALIAS/RELATED ITEM]
      ,[PRICING ALIAS/RELATED ITEM]
      ,[ALIAS/RELATED ITEM]
      ,[CUSTOMER STYLE]
      ,[CUSTOMER''S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS]
      ,[ACTIVE]
      ,[All]
      ,[Multiple Items]
      ,[FACILITY CODE]
      ,[BULK AGREEMENT NUMBER]
      ,[Sum of TOTAL QTY]
      ,[BULK AGREEMENT DESCRIPTION]
      ,[CUSTOMER CODE]
      ,[CO NUMBER - INITIAL DISTRO]
      ,[CO NUMBER (INITIAL DISTRO)]
      ,[CO NUMBER (ALLOCATION DISTRO)]
      ,[CO NUMBER - ALLOCATION DISTRO]
      ,[PO NUMBER]
      ,[AAG SEASON CODE]
      ,[INFOR MAKE/BUY CODE]
      ,[PLANNER2]
      ,[ITEM TYPE CODE]
      ,[INFOR ITEM TYPE CODE]
      ,[PRODUCT GROUP CODE]
      ,[MAKE/BUY CODE]
      ,[INFOR PRODUCT GROUP CODE]
      ,[ITEM GROUP CODE]
      ,[STYLE DESCRIPTION]
      ,[INFOR ITEM GROUP CODE]
      ,[GENDER GROUP CODE]
      ,[INFOR GENDER GROUP CODE]
      ,[FABRIC TYPE CODE]
      ,[INFOR FABRIC TYPE CODE]
      ,[CUSTOMER COLOUR DESCRIPTION]
      ,[UNIT OF MEASURE]
      ,[INFOR COLOUR CODE]
      ,[XXXS]
      ,[XXS]
      ,[XS]
      ,[S]
      ,[S/M]
      ,[M]
      ,[M/L]
      ,[L]
      ,[L/XL]
      ,[XL]
      ,[XXL]
      ,[XXXL]
      ,[0]
      ,[2]
      ,[4]
      ,[6]
      ,[8]
      ,[10]
      ,[12]
      ,[14]
      ,[16]
      ,[18]
      ,[20]
      ,[0-3M]
      ,[3-6M]
      ,[6-9M]
      ,[9-12M]
      ,[12-18M]
      ,[18-24M]
      ,[2T]
      ,[3T]
      ,[4T]
      ,[5T]
      ,[6T]
      ,[30/30]
      ,[30/32]
      ,[32/30]
      ,[32/32]
      ,[34/30]
      ,[34/32]
      ,[36/30]
      ,[36/32]
      ,[32C]
      ,[32D]
      ,[32DD]
      ,[34C]
      ,[34D]
      ,[34DD]
      ,[36C]
      ,[36D]
      ,[36DD]
      ,[OS]
      ,[ONE SIZE]
      ,[0w]
      ,[10w]
      ,[12w]
      ,[1X]
      ,[2/3]
      ,[22]
      ,[24]
      ,[26]
      ,[27]
      ,[28]
      ,[28-30L]
      ,[29]
      ,[2w]
      ,[2X]
      ,[2XL]
      ,[30]
      ,[30-30L]
      ,[30-31L]
      ,[30-32L]
      ,[30X30]
      ,[31]
      ,[31/30]
      ,[31/32]
      ,[31-30L]
      ,[31-31L]
      ,[31-32L]
      ,[31X30]
      ,[32]
      ,[32/34]
      ,[32/36]
      ,[32-30L]
      ,[32-31L]
      ,[32-32L]
      ,[32DDD]
      ,[32X30]
      ,[33]
      ,[33/30]
      ,[33/32]
      ,[33-30L]
      ,[33-31L]
      ,[33-32L]
      ,[34]
      ,[34/34]
      ,[34-30L]
      ,[34-31L]
      ,[34-32L]
      ,[34DDD]
      ,[34X30]
      ,[35]
      ,[35/30]
      ,[35/32]
      ,[35-30L]
      ,[35-31L]
      ,[35-32L]
      ,[36]
      ,[36/34]
      ,[36-30L]
      ,[36-31L]
      ,[36-32L]
      ,[36DDD]
      ,[36X30]
      ,[38]
      ,[38/30]
      ,[38/32]
      ,[38/34]
      ,[38/36]
      ,[38-30L]
      ,[38-31L]
      ,[38-32L]
      ,[38C]
      ,[38D]
      ,[38DD]
      ,[38DDD]
      ,[38X30]
      ,[3X]
      ,[3XL]
      ,[4/5]
      ,[40]
      ,[40/30]
      ,[40/32]
      ,[40-30L]
      ,[40-31L]
      ,[40X30]
      ,[42]
      ,[44]
      ,[46]
      ,[48]
      ,[4w]
      ,[4X]
      ,[4XL]
      ,[4XT]
      ,[5]
      ,[50]
      ,[52]
      ,[54]
      ,[56]
      ,[58]
      ,[6/7]
      ,[60]
      ,[6w]
      ,[7]
      ,[8w]
      ,[9]
      ,[L(10-12)]
      ,[L(14-16)]
      ,[M(10-12)]
      ,[M(8-10)]
      ,[S(6-8)]
      ,[TOTAL QTY]
      ,[ORDER TYPE]
      ,[DESTINATION]
      ,[DESTINATION WAREHOUSE]
      ,[ALLOCATION (CHANNEL)]
      ,[SHOP NAME]
      ,[COLLECTION DELIVERY]
      ,[SHOP CODE]
      ,[TRACKING NUMBER]
      ,[ETA CUSTOMER WAREHOUSE DATE]
      ,[EX FACTORY DATE]
      ,[DELIVERY TERMS]
      ,[PLANNED DELIVERY METHOD]
      ,[DELIVERY CODE (MODL)]
      ,[NOTES]
      ,[VALIDATION]
      ,[VALIDATION2]
      ,[VALIDATION3]
      ,[VALIDATION4]
      ,[CUSTOMER PRICE]
      ,[USA ONLY LSTP 75% EX WORKS]
      ,[EX WORKS (USD)]
      ,[ADMINISTRATION FEE]
      ,[DESIGN FEE]
      ,[FX CHARGE]
      ,[HANDLING]
      ,[PNP]
      ,[SURCHARGE FEE]
      ,[DISCOUNT]
      ,[FINAL FOB (USD)]
      ,[HS CODE]
      ,[US DUTY RATE]
      ,[US DUTY]
      ,[FREIGHT]
      ,[US TARIFF RATE]
      ,[US TARIFF]
      ,[DDP US (USD)]
      ,[UK DUTY RATE]
      ,[UK FREIGHT]
      ,[UK INSURANCE]
      ,[UK CIF]
      ,[UK DUTY]
      ,[DDP UK (USD)]
      ,[CAN DUTY RATE]
      ,[CAN DUTY]
      ,[DDP CAN (USD)]
      ,[SMS PRICE USD]
      ,[FINAL PRICES Y/N]
      ,[NOTES FOR PRICE]
      ,[PRICING NOTES]
      ,[Delta]
      ,[Warehouse]
      ,[ORTP (ORDER TYPE)]
      ,[Longson Alias]
      ,[BUAR (BUSINESS AREA UNIT)]
      ,[ADID]
  FROM [dbo].[ORDERS_UNIFIED]
  where [AAG ORDER NUMBER] = 'JOO-00505'