let
    Source = Sql.Database("ross-db-srv-test.database.windows.net", "ORDERS", [Query="Select * from ORDERS_UNIFIED"]),
    #"Replaced Value4" = Table.ReplaceValue(Source,"TRUE","0",Replacer.ReplaceText,{"US TARIFF RATE"}),
    #"Added Index" = Table.AddIndexColumn(#"Replaced Value4", "Index", 0, 1, Int64.Type),
    #"Reordered Columns5" = Table.ReorderColumns(#"Added Index",{"Index", "AAG ORDER NUMBER", "CUSTOMER NAME", "ORDER DATE PO RECEIVED", "CUSTOMER ALT PO", "AAG SEASON", "CUSTOMER SEASON", "DROP", "MONTH", "RANGE / COLLECTION", "PROMO GROUP / CAMPAIGN (HOT 30/GLOBAL EDIT", "CATEGORY", "PATTERN ID", "MAKE OR BUY", "PLANNER", "ORIGINAL ALIAS/RELATED ITEM", "PRICING ALIAS/RELATED ITEM", "ALIAS/RELATED ITEM", "CUSTOMER STYLE", "CUSTOMER''S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS", "ACTIVE", "All", "Multiple Items", "FACILITY CODE", "BULK AGREEMENT NUMBER", "Sum of TOTAL QTY", "BULK AGREEMENT DESCRIPTION", "CUSTOMER CODE", "CO NUMBER - INITIAL DISTRO", "CO NUMBER (INITIAL DISTRO)", "CO NUMBER (ALLOCATION DISTRO)", "CO NUMBER - ALLOCATION DISTRO", "PO NUMBER", "AAG SEASON CODE", "INFOR MAKE/BUY CODE", "PLANNER2", "ITEM TYPE CODE", "INFOR ITEM TYPE CODE", "PRODUCT GROUP CODE", "MAKE/BUY CODE", "INFOR PRODUCT GROUP CODE", "ITEM GROUP CODE", "STYLE DESCRIPTION", "INFOR ITEM GROUP CODE", "GENDER GROUP CODE", "INFOR GENDER GROUP CODE", "FABRIC TYPE CODE", "INFOR FABRIC TYPE CODE", "CUSTOMER COLOUR DESCRIPTION", "UNIT OF MEASURE", "INFOR COLOUR CODE", "XXXS", "XXS", "XS", "S", "S/M", "M", "M/L", "L", "L/XL", "XL", "XXL", "XXXL", "0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "4XT", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "DELIVERY CODE (MODL)", "NOTES", "VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "PNP", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns5", each Date.IsInCurrentYear([ORDER DATE PO RECEIVED])),
    #"Replaced Value2" = Table.ReplaceValue(#"Filtered Rows","RHYTHM (AU)","RHYTHM",Replacer.ReplaceText,{"CUSTOMER NAME"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","RHYTHM (US)","RHYTHM",Replacer.ReplaceText,{"CUSTOMER NAME"}),
    #"Merged Queries" = Table.NestedJoin(#"Replaced Value3", {"CUSTOMER NAME"}, Customers, {"Customer_Map_MOL"}, "Customers", JoinKind.LeftOuter),
    #"Expanded Customers" = Table.ExpandTableColumn(#"Merged Queries", "Customers", {"CUSTOMER_Dropdown"}, {"CUSTOMER_Dropdown"}),
    #"Sorted Rows1" = Table.Sort(#"Expanded Customers",{{"Index", Order.Ascending}}),
    #"Reordered Columns6" = Table.ReorderColumns(#"Sorted Rows1",{"Index", "AAG ORDER NUMBER", "CUSTOMER NAME", "CUSTOMER_Dropdown", "ORDER DATE PO RECEIVED", "CUSTOMER ALT PO", "AAG SEASON", "CUSTOMER SEASON", "DROP", "MONTH", "RANGE / COLLECTION", "PROMO GROUP / CAMPAIGN (HOT 30/GLOBAL EDIT", "CATEGORY", "PATTERN ID", "MAKE OR BUY", "PLANNER", "ORIGINAL ALIAS/RELATED ITEM", "PRICING ALIAS/RELATED ITEM", "ALIAS/RELATED ITEM", "CUSTOMER STYLE", "CUSTOMER''S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS", "ACTIVE", "All", "Multiple Items", "FACILITY CODE", "BULK AGREEMENT NUMBER", "Sum of TOTAL QTY", "BULK AGREEMENT DESCRIPTION", "CUSTOMER CODE", "CO NUMBER - INITIAL DISTRO", "CO NUMBER (INITIAL DISTRO)", "CO NUMBER (ALLOCATION DISTRO)", "CO NUMBER - ALLOCATION DISTRO", "PO NUMBER", "AAG SEASON CODE", "INFOR MAKE/BUY CODE", "PLANNER2", "ITEM TYPE CODE", "INFOR ITEM TYPE CODE", "PRODUCT GROUP CODE", "MAKE/BUY CODE", "INFOR PRODUCT GROUP CODE", "ITEM GROUP CODE", "STYLE DESCRIPTION", "INFOR ITEM GROUP CODE", "GENDER GROUP CODE", "INFOR GENDER GROUP CODE", "FABRIC TYPE CODE", "INFOR FABRIC TYPE CODE", "CUSTOMER COLOUR DESCRIPTION", "UNIT OF MEASURE", "INFOR COLOUR CODE", "XXXS", "XXS", "XS", "S", "S/M", "M", "M/L", "L", "L/XL", "XL", "XXL", "XXXL", "0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "4XT", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "DELIVERY CODE (MODL)", "NOTES", "VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "PNP", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Reordered Columns6",{"CUSTOMER NAME", "AAG ORDER NUMBER", "ORDER DATE PO RECEIVED", "CUSTOMER ALT PO", "AAG SEASON", "CUSTOMER SEASON", "DROP", "MONTH", "RANGE / COLLECTION", "PROMO GROUP / CAMPAIGN (HOT 30/GLOBAL EDIT", "CATEGORY", "PATTERN ID", "MAKE OR BUY", "PLANNER", "ORIGINAL ALIAS/RELATED ITEM", "PRICING ALIAS/RELATED ITEM", "ALIAS/RELATED ITEM", "CUSTOMER STYLE", "CUSTOMER''S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS", "ACTIVE", "All", "Multiple Items", "FACILITY CODE", "BULK AGREEMENT NUMBER", "Sum of TOTAL QTY", "BULK AGREEMENT DESCRIPTION", "CUSTOMER CODE", "CO NUMBER - INITIAL DISTRO", "CO NUMBER (INITIAL DISTRO)", "CO NUMBER (ALLOCATION DISTRO)", "CO NUMBER - ALLOCATION DISTRO", "PO NUMBER", "AAG SEASON CODE", "INFOR MAKE/BUY CODE", "PLANNER2", "ITEM TYPE CODE", "INFOR ITEM TYPE CODE", "PRODUCT GROUP CODE", "MAKE/BUY CODE", "INFOR PRODUCT GROUP CODE", "ITEM GROUP CODE", "STYLE DESCRIPTION", "INFOR ITEM GROUP CODE", "GENDER GROUP CODE", "INFOR GENDER GROUP CODE", "FABRIC TYPE CODE", "INFOR FABRIC TYPE CODE", "CUSTOMER COLOUR DESCRIPTION", "UNIT OF MEASURE", "INFOR COLOUR CODE", "XXXS", "XXS", "XS", "S", "S/M", "M", "M/L", "L", "L/XL", "XL", "XXL", "XXXL", "0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "4XT", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "DELIVERY CODE (MODL)", "NOTES", "VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "PNP", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Filtered Rows1" = Table.SelectRows(#"Reordered Columns", each ([CUSTOMER_Dropdown] <> null)),
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows1",{{"ORDER DATE PO RECEIVED", type date}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type",{"CUSTOMER NAME", "AAG ORDER NUMBER", "ORDER DATE PO RECEIVED", "CUSTOMER SEASON", "DROP", "AAG SEASON", "MONTH", "RANGE / COLLECTION", "CATEGORY", "PATTERN ID", "MAKE OR BUY", "PLANNER", "ORIGINAL ALIAS/RELATED ITEM", "PRICING ALIAS/RELATED ITEM", "ALIAS/RELATED ITEM", "CUSTOMER STYLE", "CUSTOMER''S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS", "ACTIVE", "All", "Multiple Items", "FACILITY CODE", "BULK AGREEMENT NUMBER", "Sum of TOTAL QTY", "BULK AGREEMENT DESCRIPTION", "CUSTOMER CODE", "CO NUMBER - INITIAL DISTRO", "CO NUMBER (INITIAL DISTRO)", "CO NUMBER (ALLOCATION DISTRO)", "CO NUMBER - ALLOCATION DISTRO", "PO NUMBER", "AAG SEASON CODE", "INFOR MAKE/BUY CODE", "PLANNER2", "ITEM TYPE CODE", "INFOR ITEM TYPE CODE", "PRODUCT GROUP CODE", "MAKE/BUY CODE", "INFOR PRODUCT GROUP CODE", "ITEM GROUP CODE", "STYLE DESCRIPTION", "INFOR ITEM GROUP CODE", "GENDER GROUP CODE", "INFOR GENDER GROUP CODE", "FABRIC TYPE CODE", "INFOR FABRIC TYPE CODE", "CUSTOMER COLOUR DESCRIPTION", "UNIT OF MEASURE", "INFOR COLOUR CODE", "XXXS", "XXS", "XS", "S", "S/M", "M", "M/L", "L", "L/XL", "XL", "XXL", "XXXL", "0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "4XT", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "DELIVERY CODE (MODL)", "NOTES", "VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "PNP", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns1",{"MONTH", "RANGE / COLLECTION",  "MAKE OR BUY", "PLANNER", "PRICING ALIAS/RELATED ITEM", "ALIAS/RELATED ITEM", "CUSTOMER''S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS", "Multiple Items", "FACILITY CODE", "BULK AGREEMENT NUMBER", "Sum of TOTAL QTY", "BULK AGREEMENT DESCRIPTION", "CUSTOMER CODE", "CO NUMBER - INITIAL DISTRO", "CO NUMBER (INITIAL DISTRO)", "CO NUMBER (ALLOCATION DISTRO)", "CO NUMBER - ALLOCATION DISTRO"}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns1",{"CUSTOMER NAME", "AAG ORDER NUMBER", "AAG SEASON", "ORDER DATE PO RECEIVED", "CUSTOMER SEASON", "DROP", "PO NUMBER", "CUSTOMER STYLE", "CATEGORY", "PATTERN ID", "ACTIVE", "All", "AAG SEASON CODE", "INFOR MAKE/BUY CODE", "PLANNER2", "ITEM TYPE CODE", "INFOR ITEM TYPE CODE", "PRODUCT GROUP CODE", "MAKE/BUY CODE", "INFOR PRODUCT GROUP CODE", "ITEM GROUP CODE", "STYLE DESCRIPTION", "INFOR ITEM GROUP CODE", "GENDER GROUP CODE", "INFOR GENDER GROUP CODE", "FABRIC TYPE CODE", "INFOR FABRIC TYPE CODE", "CUSTOMER COLOUR DESCRIPTION", "UNIT OF MEASURE", "INFOR COLOUR CODE", "XXXS", "XXS", "XS", "S", "S/M", "M", "M/L", "L", "L/XL", "XL", "XXL", "XXXL", "0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "4XT", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "DELIVERY CODE (MODL)", "NOTES", "VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "PNP", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns2",{"ACTIVE", "All", "AAG SEASON CODE", "INFOR MAKE/BUY CODE", "PLANNER2", "ITEM TYPE CODE", "INFOR ITEM TYPE CODE", "PRODUCT GROUP CODE", "MAKE/BUY CODE", "INFOR PRODUCT GROUP CODE", "ITEM GROUP CODE"}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Removed Columns2",{"CUSTOMER NAME", "AAG ORDER NUMBER", "AAG SEASON", "ORDER DATE PO RECEIVED", "CUSTOMER SEASON", "DROP", "PO NUMBER", "CUSTOMER STYLE", "STYLE DESCRIPTION", "CATEGORY", "PATTERN ID", "INFOR ITEM GROUP CODE", "GENDER GROUP CODE", "INFOR GENDER GROUP CODE", "FABRIC TYPE CODE", "INFOR FABRIC TYPE CODE", "CUSTOMER COLOUR DESCRIPTION", "UNIT OF MEASURE", "INFOR COLOUR CODE", "XXXS", "XXS", "XS", "S", "S/M", "M", "M/L", "L", "L/XL", "XL", "XXL", "XXXL", "0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "4XT", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "DELIVERY CODE (MODL)", "NOTES", "VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "PNP", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns3",{"INFOR ITEM GROUP CODE", "GENDER GROUP CODE", "INFOR GENDER GROUP CODE", "FABRIC TYPE CODE", "INFOR FABRIC TYPE CODE"}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Removed Columns3",{"CUSTOMER NAME", "AAG ORDER NUMBER", "AAG SEASON", "ORDER DATE PO RECEIVED", "CUSTOMER SEASON", "DROP", "PO NUMBER", "CUSTOMER STYLE", "STYLE DESCRIPTION", "CUSTOMER COLOUR DESCRIPTION", "CATEGORY", "PATTERN ID", "UNIT OF MEASURE", "INFOR COLOUR CODE", "XXXS", "XXS", "XS", "S", "S/M", "M", "M/L", "L", "L/XL", "XL", "XXL", "XXXL", "0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "4XT", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "DELIVERY CODE (MODL)", "NOTES", "VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "PNP", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Removed Columns4" = Table.RemoveColumns(#"Reordered Columns4",{"INFOR COLOUR CODE", "XXXS", "XXS", "S/M", "M/L", "L/XL"}),
    #"Removed Columns5" = Table.RemoveColumns(#"Removed Columns4",{"0", "2", "4", "6", "8", "10", "12", "14", "16", "18", "20", "0-3M", "3-6M", "6-9M", "9-12M", "12-18M", "18-24M", "2T", "3T", "4T", "5T", "6T", "30/30", "30/32", "32/30", "32/32", "34/30", "34/32", "36/30", "36/32", "32C", "32D", "32DD", "34C", "34D", "34DD", "36C", "36D", "36DD", "OS", "ONE SIZE", "0w", "10w", "12w", "1X", "2/3", "22", "24", "26", "27", "28", "28-30L", "29", "2w", "2X", "2XL", "30", "30-30L", "30-31L", "30-32L", "30X30", "31", "31/30", "31/32", "31-30L", "31-31L", "31-32L", "31X30", "32", "32/34", "32/36", "32-30L", "32-31L", "32-32L", "32DDD", "32X30", "33", "33/30", "33/32", "33-30L", "33-31L", "33-32L", "34", "34/34", "34-30L", "34-31L", "34-32L", "34DDD", "34X30", "35", "35/30", "35/32", "35-30L", "35-31L", "35-32L", "36", "36/34", "36-30L", "36-31L", "36-32L", "36DDD", "36X30", "38", "38/30", "38/32", "38/34", "38/36", "38-30L", "38-31L", "38-32L", "38C", "38D", "38DD", "38DDD", "38X30", "3X", "3XL", "4/5", "40", "40/30", "40/32", "40-30L", "40-31L", "40X30", "42", "44", "46", "48", "4w", "4X", "4XL", "5", "50", "52", "54", "56", "58", "6/7", "60", "6w", "7", "8w", "9", "L(10-12)", "L(14-16)", "M(10-12)", "M(8-10)", "S(6-8)", "ALLOCATION (CHANNEL)", "SHOP NAME", "COLLECTION DELIVERY", "SHOP CODE", "TRACKING NUMBER"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns5",{{"ETA CUSTOMER WAREHOUSE DATE", type date}, {"EX FACTORY DATE", type date}}),
    #"Removed Columns6" = Table.RemoveColumns(#"Changed Type1",{"VALIDATION", "VALIDATION2", "VALIDATION3", "VALIDATION4"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns6",{{"CUSTOMER PRICE", type number}, {"USA ONLY LSTP 75% EX WORKS", type number}, {"EX WORKS (USD)", type number}, {"ADMINISTRATION FEE", type number}, {"FX CHARGE", type number}, {"DESIGN FEE", type number}, {"HANDLING", type number}, {"PNP", type number}, {"SURCHARGE FEE", type number}, {"DISCOUNT", type number}, {"FINAL FOB (USD)", type number}, {"US DUTY RATE", Percentage.Type}, {"US DUTY", type number}, {"US TARIFF RATE", Percentage.Type}, {"FREIGHT", type number}, {"US TARIFF", type number}, {"DDP US (USD)", type number}}),
    #"Removed Columns7" = Table.RemoveColumns(#"Changed Type2",{"UK DUTY RATE", "UK FREIGHT", "UK INSURANCE", "UK CIF", "UK DUTY", "DDP UK (USD)", "CAN DUTY RATE", "CAN DUTY", "DDP CAN (USD)", "Warehouse", "ORTP (ORDER TYPE)", "Longson Alias", "BUAR (BUSINESS AREA UNIT)", "ADID"}),
    #"Trimmed Text" = Table.TransformColumns(#"Removed Columns7",{{"CUSTOMER STYLE", Text.Trim, type text}, {"STYLE DESCRIPTION", Text.Trim, type text}, {"CUSTOMER COLOUR DESCRIPTION", Text.Trim, type text}}),
    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"CUSTOMER STYLE", Text.Clean, type text}, {"STYLE DESCRIPTION", Text.Clean, type text}, {"CUSTOMER COLOUR DESCRIPTION", Text.Clean, type text}}),
    #"Removed Columns8" = Table.RemoveColumns(#"Cleaned Text",{"PROMO GROUP / CAMPAIGN (HOT 30/GLOBAL EDIT", "DELIVERY CODE (MODL)", "PNP"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns8","TITLE 9","TITLE NINE",Replacer.ReplaceText,{"CUSTOMER NAME"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,#date(1900, 1, 1),Replacer.ReplaceValue,{"ETA CUSTOMER WAREHOUSE DATE"})
in
    #"Replaced Value1"


    let
    Source = ConvertDateColumns(Master_Order_List),
    #"Added Custom" = Table.AddColumn(Source, "Name", each [CUSTOMER STYLE] & [CUSTOMER COLOUR DESCRIPTION] & [AAG ORDER NUMBER]),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"Name", "CUSTOMER NAME", "AAG ORDER NUMBER", "AAG SEASON", "ORDER DATE PO RECEIVED", "CUSTOMER SEASON", "DROP", "PO NUMBER", "CUSTOMER STYLE", "STYLE DESCRIPTION", "CUSTOMER COLOUR DESCRIPTION", "CATEGORY", "PATTERN ID", "UNIT OF MEASURE", "XS", "S", "M", "L", "XL", "XXL", "XXXL", "4XT", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "ETA CUSTOMER WAREHOUSE DATE", "EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "NOTES", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE", "PRICING NOTES", "Delta"}),
    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"PRICING NOTES", "Delta", "CATEGORY"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ETA CUSTOMER WAREHOUSE DATE", "CUSTOMER REQ IN DC DATE"}, {"EX FACTORY DATE", "CUSTOMER EX FACTORY DATE"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","ACTIVE","RECEIVED",Replacer.ReplaceText,{"ORDER TYPE"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value",{{"CUSTOMER STYLE", "STYLE"}, {"CUSTOMER COLOUR DESCRIPTION", "COLOR"}, {"CUSTOMER NAME", "CUSTOMER"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns1",{"Index", "XS", "S", "M", "L", "XL", "XXL", "XXXL", "4XT", "CUSTOMER"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Removed Columns1",{{"CUSTOMER_Dropdown", "CUSTOMER"}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns2",{"Name", "CUSTOMER", "AAG ORDER NUMBER", "AAG SEASON", "ORDER DATE PO RECEIVED", "CUSTOMER SEASON", "DROP", "PO NUMBER", "CUSTOMER ALT PO", "STYLE", "PATTERN ID", "ORIGINAL ALIAS/RELATED ITEM", "STYLE DESCRIPTION", "COLOR", "UNIT OF MEASURE", "TOTAL QTY", "ORDER TYPE", "DESTINATION", "DESTINATION WAREHOUSE", "CUSTOMER REQ IN DC DATE", "CUSTOMER EX FACTORY DATE", "DELIVERY TERMS", "PLANNED DELIVERY METHOD", "NOTES", "CUSTOMER PRICE", "USA ONLY LSTP 75% EX WORKS", "EX WORKS (USD)", "ADMINISTRATION FEE", "DESIGN FEE", "FX CHARGE", "HANDLING", "SURCHARGE FEE", "DISCOUNT", "FINAL FOB (USD)", "HS CODE", "US DUTY RATE", "US DUTY", "FREIGHT", "US TARIFF RATE", "US TARIFF", "DDP US (USD)", "SMS PRICE USD", "FINAL PRICES Y/N", "NOTES FOR PRICE"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns1",{{"ORIGINAL ALIAS/RELATED ITEM", "ALIAS RELATED ITEM"}})
in
    #"Renamed Columns3"