IF EXISTS (SELECT * FROM sys.objects WHERE name = 'ORDER_LIST' AND type = 'U')
    DROP TABLE ORDER_LIST;
GO

CREATE TABLE [dbo].[ORDER_LIST] (
    [ID] INT IDENTITY(1,1) PRIMARY KEY,

    -- Order Details
    [AAG ORDER NUMBER] NVARCHAR(100),
    [UNIT OF MEASURE] NVARCHAR(100),

    -- Garment Sizes (All INT)
    [ONE SIZE] INT,

    -- Additional Order Details
    [INFOR WAREHOUSE CODE] NVARCHAR(255)
,
    [INFOR FACILITY CODE] NVARCHAR(255)
,
    [INFOR BUSINESS UNIT AREA] NVARCHAR(100)
,
    [CUSTOMER NAME] NVARCHAR(100)
,
    [INFOR CUSTOMER CODE] NVARCHAR(100)
,
    [CO NUMBER (INITIAL DISTRO)] NVARCHAR(255)
,
    [CO NUMBER (ALLOCATION DISTRO)] NVARCHAR(255)
,
    [ORDER DATE PO RECEIVED] NVARCHAR(100)
,
    [INFOR ORDER TYPE] NVARCHAR(255)
,
    [PO NUMBER] NVARCHAR(100)
,
    [CUSTOMER ALT PO] NVARCHAR(255)
,
    [AAG SEASON] NVARCHAR(100)
,
    [CUSTOMER SEASON] NVARCHAR(100)
,
    [INFOR SEASON CODE] NVARCHAR(100)
,
    [DROP] NVARCHAR(100)
,
    [MONTH] NVARCHAR(255)
,
    [RANGE / COLLECTION] NVARCHAR(100)
,
    [PROMO GROUP / CAMPAIGN (HOT 30/GLOBAL EDIT] NVARCHAR(255)
,
    [CATEGORY] NVARCHAR(255)
,
    [PATTERN ID] NVARCHAR(255)
,
    [PLANNER] NVARCHAR(100)
,
    [PLANNER2] NVARCHAR(255)
,
    [MAKE OR BUY] NVARCHAR(100)
,
    [INFOR MAKE/BUY CODE] NVARCHAR(100)
,
    [INFOR ITEM TYPE CODE] NVARCHAR(100)
,
    [INFOR PRODUCT GROUP CODE] NVARCHAR(100)
,
    [INFOR ITEM GROUP CODE] NVARCHAR(100)
,
    [INFOR GENDER GROUP CODE] NVARCHAR(100)
,
    [INFOR FABRIC TYPE CODE] NVARCHAR(100)
,
    [ORIGINAL ALIAS/RELATED ITEM] NVARCHAR(255)
,
    [PRICING ALIAS/RELATED ITEM] NVARCHAR(255)
,
    [ALIAS/RELATED ITEM] NVARCHAR(100)
,
    [CUSTOMER STYLE] NVARCHAR(100)
,
    [LONGSON ALIAS] NVARCHAR(255)
,
    [STYLE DESCRIPTION] NVARCHAR(100)
,
    [CUSTOMER'S COLOUR CODE (CUSTOM FIELD) CUSTOMER PROVIDES THIS] NVARCHAR(255)
,
    [CUSTOMER COLOUR DESCRIPTION] NVARCHAR(100)
,
    [INFOR COLOUR CODE] NVARCHAR(255)
,
    [XS-PETITE] NVARCHAR(100)
,
    [S-PETITE] NVARCHAR(100)
,
    [XXS] NVARCHAR(100)
,
    [XS] NVARCHAR(100)
,
    [S] NVARCHAR(100)
,
    [M] NVARCHAR(100)
,
    [L] NVARCHAR(100)
,
    [XL] NVARCHAR(100)
,
    [XXL] NVARCHAR(100)
,
    [S/P] NVARCHAR(100)
,
    [S+] NVARCHAR(100)
,
    [XS/S] NVARCHAR(100)
,
    [S/M] NVARCHAR(100)
,
    [M/L] NVARCHAR(100)
,
    [L/XL] NVARCHAR(100)
,
    [XL/XXL] NVARCHAR(100)
,
    [6-12M] NVARCHAR(100)
,
    [1Y] NVARCHAR(100)
,
    [2Y] NVARCHAR(100)
,
    [3Y] NVARCHAR(100)
,
    [4Y] NVARCHAR(100)
,
    [TOTAL QTY] NVARCHAR(100)
,
    [DESTINATION] NVARCHAR(100)
,
    [DESTINATION WAREHOUSE] NVARCHAR(100)
,
    [ALLOCATION (CHANNEL)] NVARCHAR(100)
,
    [INFOR ADDRESS ID] NVARCHAR(255)
,
    [TRACKING NUMBER] NVARCHAR(255)
,
    [SHOP NAME] NVARCHAR(255)
,
    [SHOP CODE] NVARCHAR(255)
,
    [COLLECTION DELIVERY] NVARCHAR(255)
,
    [ETA CUSTOMER WAREHOUSE DATE] NVARCHAR(100)
,
    [EX FACTORY DATE] NVARCHAR(100)
,
    [DELIVERY TERMS] NVARCHAR(100)
,
    [PLANNED DELIVERY METHOD] NVARCHAR(100)
,
    [INFOR DELIVERY CODE] NVARCHAR(255)
,
    [NOTES] NVARCHAR(500)
,
    [ORDER TYPE] NVARCHAR(100)
,
    [VALIDATION] NVARCHAR(100)
,
    [VALIDATION2] NVARCHAR(255)
,
    [VALIDATION3] NVARCHAR(255)
,
    [VALIDATION4] NVARCHAR(255)
,
    [CUSTOMER PRICE] NVARCHAR(100)
,
    [USA ONLY LSTP 75% EX WORKS] NVARCHAR(100)
,
    [EX WORKS (USD)] NVARCHAR(100)
,
    [ADMINISTRATION FEE] NVARCHAR(100)
,
    [DESIGN FEE] NVARCHAR(255)
,
    [FX CHARGE] NVARCHAR(100)
,
    [HANDLING] NVARCHAR(100)
,
    [PNP] NVARCHAR(255)
,
    [SURCHARGE FEE] NVARCHAR(100)
,
    [DISCOUNT] NVARCHAR(100)
,
    [FINAL FOB (USD)] NVARCHAR(100)
,
    [HS CODE] NVARCHAR(100)
,
    [US DUTY RATE] NVARCHAR(255)
,
    [US DUTY] NVARCHAR(255)
,
    [FREIGHT] NVARCHAR(255)
,
    [US TARIFF RATE] NVARCHAR(255)
,
    [US TARIFF] NVARCHAR(255)
,
    [DDP US (USD)] NVARCHAR(255)
,
    [UK DUTY RATE] NVARCHAR(255)
,
    [UK FREIGHT] NVARCHAR(255)
,
    [UK INSURANCE] NVARCHAR(255)
,
    [UK CIF] NVARCHAR(255)
,
    [UK DUTY] NVARCHAR(255)
,
    [DDP UK (USD)] NVARCHAR(255)
,
    [CAN DUTY RATE] NVARCHAR(255)
,
    [CAN DUTY] NVARCHAR(255)
,
    [DDP CAN (USD)] NVARCHAR(255)
,
    [SMS PRICE USD] NVARCHAR(100)
,
    [FINAL PRICES Y/N] NVARCHAR(100)
    [NOTES FOR PRICE] NVARCHAR(255)
    [∆] NVARCHAR(100)
    [HDPR] NVARCHAR(100)
);
GO