id: extract_board_8738178586
namespace: monday.boards

description: "Extract data from Monday.com board: Partner Purchase Orders"

tasks:
  - id: extract_board_data
    type: io.kestra.plugin.scripts.python.Script
    description: "Extract board 8738178586 using unified loader"
    script: |
      python pipelines/scripts/load_boards.py --board-id 8738178586
    
  - id: validate_data
    type: io.kestra.plugin.scripts.python.Script
    description: "Validate extracted data"
    script: |
      python tests/validation/validate_board_8738178586.py

triggers:
  - id: daily_refresh
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 6 * * *"  # Daily at 6 AM
    
  - id: manual_trigger
    type: io.kestra.plugin.core.trigger.Webhook
