-- Table: dbo.FACT_timeline_LoadingPlan
-- Database: ORDERS
-- Purpose: [Add description of table purpose]
-- Dependencies: [List any dependent tables/views]

CREATE TABLE [dbo].[FACT_timeline_LoadingPlan] (
    [StyleColorPOID] INT NULL,
    [order_type] NVARCHAR(MAX) NULL,
    [planner] NVARCHAR(MAX) NULL,
    [customer] NVARCHAR(100) NULL,
    [drop] NVARCHAR(100) NULL,
    [season] NVARCHAR(100) NULL,
    [season1] NVARCHAR(100) NULL,
    [aag_order_no] NVARCHAR(MAX) NULL,
    [po] NVARCHAR(100) NULL,
    [essential_core_acc] NVARCHAR(MAX) NULL,
    [style] NVARCHAR(100) NULL,
    [alias] NVARCHAR(100) NULL,
    [style_category] NVARCHAR(MAX) NULL,
    [color] NVARCHAR(255) NULL,
    [po_qty] BIGINT NULL,
    [active_woven_swim_acc_seamless] NVARCHAR(MAX) NULL,
    [customer_request_exfty_date] DATE NULL,
    [revised_exfty_date] DATE NULL,
    [printing_embroider_washing_bonding] NVARCHAR(MAX) NULL,
    [print_fabric] NVARCHAR(MAX) NULL,
    [panel_printing_garment_print] NVARCHAR(MAX) NULL,
    [embroidery] NVARCHAR(MAX) NULL,
    [heat_press] NVARCHAR(MAX) NULL,
    [bonding] NVARCHAR(MAX) NULL,
    [beading] NVARCHAR(MAX) NULL,
    [lasercut] NVARCHAR(MAX) NULL,
    [quilting] NVARCHAR(MAX) NULL,
    [embossing_debossing] NVARCHAR(MAX) NULL,
    [smocking_pleating] NVARCHAR(MAX) NULL,
    [washing] NVARCHAR(MAX) NULL,
    [fuzing] NVARCHAR(MAX) NULL,
    [shipped_date] DATE NULL,
    [mo_release_date] DATE NULL,
    [mo_number] NVARCHAR(MAX) NULL,
    [fabric_eta_date] DATE NULL,
    [fabric_status] NVARCHAR(MAX) NULL,
    [trims_eta_date] DATE NULL,
    [trims_status] NVARCHAR(MAX) NULL,
    [pps_sign_off_date] DATE NULL,
    [pps_status] NVARCHAR(MAX) NULL,
    [factory] NVARCHAR(MAX) NULL,
    [status] NVARCHAR(MAX) NULL,
    [remarks] NVARCHAR(MAX) NULL,
    [order_received_date] DATE NULL,
    [sewing_support_gsd] FLOAT NULL,
    [total_gsd] FLOAT NULL,
    [product_cat] NVARCHAR(MAX) NULL
);
