-- Table: dbo.MES_operational_performance
-- Database: ORDERS
-- Purpose: [Add description of table purpose]
-- Dependencies: [List any dependent tables/views]

CREATE TABLE [dbo].[MES_operational_performance] (
    [MO Number] NVARCHAR(255) NULL,
    [Package_scan] FLOAT NULL,
    [Bucket_Scan] FLOAT NULL,
    [PNP_Receive] FLOAT NULL,
    [WIP_Cut] BIGINT NULL,
    [WIP_Sew] FLOAT NULL,
    [WIP_Fin] FLOAT NULL,
    [FG_Qty] FLOAT NULL,
    [master_id] BIGINT NULL,
    [order_no] NVARCHAR(255) NULL,
    [style_no] NVARCHAR(255) NULL,
    [dept_id] NVARCHAR(255) NULL,
    [closed_time] NVARCHAR(255) NULL,
    [closed_time_t] NVARCHAR(255) NULL,
    [state] NVARCHAR(255) NULL,
    [group_name] NVARCHAR(255) NULL,
    [factory_name] NVARCHAR(255) NULL,
    [dept_name] NVARCHAR(255) NULL,
    [color_name] NVARCHAR(255) NULL,
    [order_number] BIGINT NULL,
    [prep_number] FLOAT NULL,
    [cut_number] BIGINT NULL,
    [sew_number] BIGINT NULL,
    [finish_number] BIGINT NULL,
    [sample_number] BIGINT NULL,
    [defect_number] BIGINT NULL,
    [remain_number] BIGINT NULL,
    [item_no] NVARCHAR(255) NULL,
    [pre_cut] FLOAT NULL,
    [act_cut] FLOAT NULL,
    [return_cut] FLOAT NULL,
    [month_m] FLOAT NULL,
    [week_w] FLOAT NULL,
    [cut_fdate] NVARCHAR(255) NULL,
    [sew_fdate] NVARCHAR(255) NULL,
    [finish_fdate] NVARCHAR(255) NULL,
    [finish_order_rate] NVARCHAR(255) NULL,
    [finish_cut_rate] NVARCHAR(255) NULL,
    [wh01] BIGINT NULL,
    [wh02] BIGINT NULL,
    [wh03] BIGINT NULL,
    [wh05] BIGINT NULL,
    [wh07A] BIGINT NULL,
    [wh07B] BIGINT NULL,
    [wh07C] BIGINT NULL,
    [wh07H] FLOAT NULL,
    [wh09A] BIGINT NULL,
    [wh09B] BIGINT NULL,
    [wh09C] BIGINT NULL,
    [wh09H] FLOAT NULL,
    [customer_name] NVARCHAR(255) NULL,
    [create_time] NVARCHAR(255) NULL,
    [create_time_order] NVARCHAR(255) NULL,
    [cut_sdate] NVARCHAR(255) NULL,
    [sew_sdate] NVARCHAR(255) NULL,
    [finish_sdate] NVARCHAR(255) NULL,
    [customer_no] NVARCHAR(255) NULL,
    [no_in] BIGINT NULL,
    [style_sort] NVARCHAR(255) NULL,
    [Cutting WIP] BIGINT NULL,
    [Sewing WIP] FLOAT NULL,
    [Finishing WIP] FLOAT NULL,
    [work people] FLOAT NULL,
    [Attend Hrs] FLOAT NULL,
    [GSD Hrs prod] FLOAT NULL,
    [eff] FLOAT NULL,
    [work people2] FLOAT NULL,
    [Attend Hrs2] FLOAT NULL,
    [GSD Hrs prod2] FLOAT NULL,
    [eff2] FLOAT NULL,
    [work people3] FLOAT NULL,
    [Attend Hrs3] FLOAT NULL,
    [GSD Hrs prod3] FLOAT NULL,
    [eff3] FLOAT NULL,
    [dress name] NVARCHAR(255) NULL,
    [Production type] NVARCHAR(255) NULL,
    [Package scan] FLOAT NULL,
    [Bucket Scan] FLOAT NULL,
    [PNP Receive] FLOAT NULL,
    [big_ironing] FLOAT NULL,
    [process_state] FLOAT NULL,
    [abnormal_number] FLOAT NULL,
    [description] NVARCHAR(255) NULL,
    [opinion] NVARCHAR(255) NULL,
    [applicat_by] NVARCHAR(255) NULL,
    [verity_by] NVARCHAR(255) NULL,
    [verity_time] DATETIME2 NULL,
    [rn] BIGINT NULL
);
