-- Table: dbo.MON_Planning
-- Database: ORDERS
-- Purpose: [Add description of table purpose]
-- Dependencies: [List any dependent tables/views]

CREATE TABLE [dbo].[MON_Planning] (
    [name] NVARCHAR(MAX) NULL,
    [subitems] NVARCHAR(MAX) NULL,
    [season] NVARCHAR(MAX) NULL,
    [customer_season] NVARCHAR(100) NULL,
    [drop] NVARCHAR(100) NULL,
    [customer] NVARCHAR(100) NULL,
    [customer_allocation] NVARCHAR(100) NULL,
    [order_received_date] DATE NULL,
    [order_type] NVARCHAR(100) NULL,
    [bulk_po] NVARCHAR(MAX) NULL,
    [aag_order_number] NVARCHAR(MAX) NULL,
    [bulk_po_qty] BIGINT NULL,
    [style_code] NVARCHAR(MAX) NULL,
    [style_description] NVARCHAR(MAX) NULL,
    [color] NVARCHAR(MAX) NULL,
    [active_woven_swim_acc_seamless] NVARCHAR(100) NULL,
    [style_category] NVARCHAR(100) NULL,
    [product_group] NVARCHAR(100) NULL,
    [product_cat] NVARCHAR(100) NULL,
    [fabric_code] NVARCHAR(100) NULL,
    [fabric_type] NVARCHAR(100) NULL,
    [fabric_lead_time] NVARCHAR(MAX) NULL,
    [fabric_coo] NVARCHAR(MAX) NULL,
    [cmp_ls] BIGINT NULL,
    [cmp_partner] BIGINT NULL,
    [rm_freight_est] BIGINT NULL,
    [fob_partner] BIGINT NULL,
    [po_base_partner] BIGINT NULL,
    [po_other_partner] BIGINT NULL,
    [po_moq_partner] BIGINT NULL,
    [po_unit_total_partner] NVARCHAR(MAX) NULL,
    [po_total_value_partner] NVARCHAR(MAX) NULL,
    [landed_cost_longson] NVARCHAR(MAX) NULL,
    [sell_price_aagt_rmb] NVARCHAR(MAX) NULL,
    [fx_rmb_usd] NVARCHAR(MAX) NULL,
    [destination] NVARCHAR(100) NULL,
    [ls_planned_approval_date_for_pp_sample] DATE NULL,
    [fabric_due_into_longson] DATE NULL,
    [longson_rm_ex_fty] DATE NULL,
    [trims_due_into_longson] DATE NULL,
    [longson_plan_cut_date] DATE NULL,
    [ex_fty_date_original] DATE NULL,
    [ex_fty_revised_ls] DATE NULL,
    [ex_fty_partner_po] DATE NULL,
    [pp_status] NVARCHAR(100) NULL,
    [fabric_status] NVARCHAR(100) NULL,
    [trim_status] NVARCHAR(100) NULL,
    [precut_quantity] BIGINT NULL,
    [iqc_status] NVARCHAR(100) NULL,
    [translation_status] NVARCHAR(100) NULL,
    [label_check_production_returns] NVARCHAR(100) NULL,
    [fabric_visual_identification] NVARCHAR(100) NULL,
    [planned_delivery_method] NVARCHAR(100) NULL,
    [incoterms] NVARCHAR(100) NULL,
    [eta_customer_warehouse_date] DATE NULL,
    [factory] NVARCHAR(100) NULL,
    [allocation_status] NVARCHAR(100) NULL,
    [country_of_origin] NVARCHAR(100) NULL,
    [remark] NVARCHAR(MAX) NULL,
    [factory_linked] NVARCHAR(MAX) NULL,
    [production_type] NVARCHAR(MAX) NULL,
    [factory_location] NVARCHAR(MAX) NULL,
    [factory_country] NVARCHAR(MAX) NULL,
    [partner_po] NVARCHAR(MAX) NULL,
    [partner_trading_entity] NVARCHAR(MAX) NULL,
    [item_id] BIGINT NOT NULL,
    [po_approval_status] NVARCHAR(MAX) NULL,
    [po_status] NVARCHAR(MAX) NULL,
    [vap_fabric_print] NVARCHAR(100) NULL,
    [vap_fabric_fuzing] NVARCHAR(100) NULL,
    [vap_panel_print] NVARCHAR(100) NULL,
    [vap_embroidery] NVARCHAR(100) NULL,
    [vap_heat_press] NVARCHAR(100) NULL,
    [vap_bonding] NVARCHAR(100) NULL,
    [vap_beading] NVARCHAR(100) NULL,
    [vap_lasercut] NVARCHAR(100) NULL,
    [vap_quilting] NVARCHAR(100) NULL,
    [vap_embossing] NVARCHAR(100) NULL,
    [vap_smocking_pleating] NVARCHAR(100) NULL,
    [washing] NVARCHAR(100) NULL,
    [rm_status] NVARCHAR(100) NULL,
    [customer_approval] NVARCHAR(100) NULL,
    [cmp_ls_ext] NVARCHAR(MAX) NULL,
    [cmp_partner_ext] NVARCHAR(MAX) NULL,
    [target_cmp_cost_usd] BIGINT NULL,
    [cutting_method] NVARCHAR(100) NULL,
    [gsd_cutting] BIGINT NULL,
    [gsd_sewing] BIGINT NULL,
    [gsd_finishing] BIGINT NULL,
    [gsd_bonding_laser] BIGINT NULL,
    [gsd_beading] BIGINT NULL,
    [gsd_total] BIGINT NULL,
    [gsd_adj_finance] BIGINT NULL,
    [order_size] NVARCHAR(100) NULL,
    [alias] NVARCHAR(MAX) NULL,
    [fabric_ready_to_ship] DATE NULL,
    [partner_comments] NVARCHAR(MAX) NULL,
    [production_status] NVARCHAR(100) NULL,
    [allocation_ref] NVARCHAR(MAX) NULL,
    [planner] NVARCHAR(MAX) NULL,
    [fabric_ordered] NVARCHAR(100) NULL,
    [customers_linked] NVARCHAR(MAX) NULL,
    [am_linked] NVARCHAR(MAX) NULL,
    [account_manager] NVARCHAR(MAX) NULL,
    [essential_core_acc] NVARCHAR(100) NULL,
    [mo_release_date] DATE NULL,
    [mo_number] NVARCHAR(MAX) NULL,
    [ex_fty_forecast] DATE NULL,
    [qty_wip] BIGINT NULL,
    [qty_fg] BIGINT NULL,
    [qty_invoiced] BIGINT NULL,
    [qty_fcst] BIGINT NULL,
    [ex_fty_change_request] DATE NULL,
    [requested_xfd_status] NVARCHAR(100) NULL,
    [aql_type] NVARCHAR(100) NULL,
    [aql_inspection] NVARCHAR(100) NULL,
    [planned_cut_date] DATE NULL,
    [qty_wip_cut] BIGINT NULL,
    [qty_wip_sew] BIGINT NULL,
    [qty_wip_fin] BIGINT NULL,
    [qty_scrap] BIGINT NULL,
    [keycustmastsch] NVARCHAR(MAX) NULL,
    [customer_fob_usd] BIGINT NULL,
    [sell_price_to_partner_usd] NVARCHAR(MAX) NULL,
    [files] NVARCHAR(MAX) NULL,
    [people] NVARCHAR(MAX) NULL,
    [cust_master_schedule] NVARCHAR(MAX) NULL,
    [shipments_rm] NVARCHAR(MAX) NULL,
    [rm_shipment_status] NVARCHAR(MAX) NULL,
    [Item ID] BIGINT NOT NULL,
    [Item Name] NVARCHAR(500) NULL,
    [Group Title] NVARCHAR(200) NULL,
    [Updated At] DATETIME2 NULL,
    [Created At] DATETIME2 NULL,
    CONSTRAINT [PK_MON_Planning] PRIMARY KEY ([Item ID])
);

-- Indexes
CREATE INDEX [IX_MON_Planning_GroupTitle] ON [dbo].[MON_Planning] ([Group Title]);
CREATE INDEX [IX_MON_Planning_UpdatedAt] ON [dbo].[MON_Planning] ([Updated At]);
